apiVersion: v1
kind: ConfigMap
metadata:
  name: aoai-api-gateway-cm
data:
  api-router-config.json: |
    {
      "endpoints" : [
         {
           "uri": "https://oai-gr-dev.openai.azure.com/openai/deployments/dev-gpt35-turbo-instruct/completions?api-version=2023-05-15",
           "apikey" : "2f0d266d"
         },
         {
           "uri": "https://oai-gr-dev.openai.azure.com/openai/deployments/gpt-35-t-inst-01/completions?api-version=2023-05-15",
           "apikey" : "9eca9ec1"
         }
       ]
    }
