apiVersion: v1
kind: Service
metadata:
  # name: {{ include "aoai-api-gtwy-chart.fullname" . }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "aoai-api-gtwy-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aoai-api-gtwy-chart.selectorLabels" . | nindent 4 }}
